services:
  frontend_app:
    image: github-crawler_frontend
    container_name: github-crawler_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - gh-crawler-net
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    hostname: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE} #change DB if needed
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    networks:
      - gh-crawler-net
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend_app:
    image: github-crawler_backend:latest
    container_name: github-crawler_backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - gh-crawler-net
    command: [ "java", "-jar", "/app.jar", "--organization=codecentric" ]#change organization if needed
volumes:
  pgdata:
networks:
  gh-crawler-net:
    driver: bridge